name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect-changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed rust files from current PR
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            **/*.rs
            **/Cargo.toml
      
      - name: Detect Changes
        id: detect-changes
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual event detected, skipping change detection"
            echo "changed=1" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]; then
            echo "Rust files changed: ${{ steps.changed-files.outputs.changed-files }}"
            echo "changed=1" >> "$GITHUB_OUTPUT"
          else
            echo "No Rust files changed"
            echo "changed=0" >> "$GITHUB_OUTPUT"
          fi

  cargo-fmt-check:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Check formatting
      run: cargo fmt --check

  build-native:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2404, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: useblacksmith/rust-cache@v3
      with:
        prefix-key: "v1-rust" # can be updated if we need to reset caches due to non-trivial change in the dependencies (for example, custom env var were set for single workspace project)
    - name: Set up Python 3.10
      uses: useblacksmith/setup-python@v6
      with:
        python-version: "3.10"
    - name: Build
      run: cargo build --verbose
    - name: Test
      env:
        RUST_LOG: ${{ runner.debug && 'limbo_core::storage=trace' || '' }}
      run: cargo test --verbose
      timeout-minutes: 20

  clippy:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - name: Clippy
        run: |
          cargo clippy --workspace --all-features --all-targets --exclude limbo-wasm -- --deny=warnings
      - name: Clippy `limbo-wasm` crate `nodejs` feature
        run: |
          cargo clippy --package limbo-wasm --features nodejs --all-targets --no-deps -- -A clippy::all -W clippy::correctness -W clippy::perf -W clippy::suspicious --deny=warnings
      - name: Clippy `limbo-wasm` crate `web` feature
        run: |
          cargo clippy --package limbo-wasm --no-default-features --features web --all-targets --no-deps -- -A clippy::all -W clippy::correctness -W clippy::perf -W clippy::suspicious --deny=warnings

  build-wasm:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build --target nodejs bindings/wasm

  test-limbo:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 20
    steps:
      - name: Install cargo-c
        env:
          LINK: https://github.com/lu-zero/cargo-c/releases/download/v0.10.7
          CARGO_C_FILE: cargo-c-x86_64-unknown-linux-musl.tar.gz
        run: |
          curl -L $LINK/$CARGO_C_FILE | tar xz -C ~/.cargo/bin

      - uses: actions/checkout@v3

      - name: Install uv
        uses: useblacksmith/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev --all-packages

      - uses: "./.github/shared/install_sqlite"
      - name: Test
        run: make test
        timeout-minutes: 20
#      - uses: "./.github/shared/install_sqlite"
#      - name: Test with index enabled
#        run: SQLITE_EXEC="scripts/limbo-sqlite3-index-experimental" make test
#        timeout-minutes: 20
  test-sqlite:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == '1'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/shared/install_sqlite"
      - name: Test
        run: SQLITE_EXEC="sqlite3" make test-compat

